-- Envers revision info table (custom with modified_by)
CREATE TABLE revinfo (
    rev        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp   BIGINT NOT NULL,
    modified_by UUID
);

-- Users
CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    google_id       VARCHAR(255) UNIQUE NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    name            VARCHAR(255) NOT NULL,
    profile_picture VARCHAR(512),
    created_by      UUID,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    modified_by     UUID,
    modified_at     TIMESTAMP NOT NULL DEFAULT now()
);

-- Envers audit table for users
CREATE TABLE users_aud (
    id              UUID         NOT NULL,
    rev             BIGINT       NOT NULL REFERENCES revinfo(rev),
    revtype         SMALLINT,
    google_id       VARCHAR(255),
    email           VARCHAR(255),
    name            VARCHAR(255),
    profile_picture VARCHAR(512),
    created_by      UUID,
    created_at      TIMESTAMP,
    modified_by     UUID,
    modified_at     TIMESTAMP,
    PRIMARY KEY (id, rev)
);
